### ISSUE TITLE
Worker failed to boot

### ISSUE THREAD

**Issue by crcox** [stsievert/salmon#102]
I just tried to kick off a local instance in a Docker container. I pulled the latest code from Github just an hour ago, installed the latest version of `docker-ce` from their repos, and built the image running `docker build .`. I identified the image id using `sudo docker images`, and then attempted `sudo docker run <image_id>`. A full terminal dump is at the link:

[failed_start.log](https://github.com/stsievert/salmon/files/6207185/failed_start.log)

My operating system:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

My Docker version:
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by stsievert** [comment]
Salmon only launches with `docker-compose up` – that is, with the Docker Compose package ([install docs][1]). That allows the Redis server to launch (which is required) and also does other bookkeeping work (adds some volumes, exposes ports, etc).

[1]:https://docs.docker.com/compose/install/

**Comment by crcox** [comment]
After installing docker following [these](https://docs.docker.com/engine/install/ubuntu/) instructions, I did not have `docker-compose` so I thought that might have been referring to an older docker version or something... didn't realize it was a separate install. Sorry!

**Comment by crcox** [comment]
Running `docker-compose` as directed in the documentation worked. Installation of `docker-compose` was uncomplicated.

**Comment by stsievert** [comment]
I'm glad Docker compose worked! The docs link to Docker (not Docker Compose), so this error is on me (and #104 corrects that mistake).

Please keep me up to date with your progress and any issues you have, either via email or the issue tracker.
