### ISSUE TITLE
Community AMI not found

### ISSUE THREAD

**Issue by crcox** [stsievert/salmon#103]
The documentation indicates that there should be a community AMI for launching on EC2 that can be found by searching for Salmon. This documentation appears to be out of date. Is there a revised method for launching Salmon on EC2?

![Screenshot](https://user-images.githubusercontent.com/2721307/112538371-cde99d80-8d7d-11eb-8b29-cfc1e8af2d8e.PNG)

**Comment by stsievert** [comment]
Are you in the Oregon/us-west-2 region? You can change the region in the upper right. I am seeing the Salmon AMI appear in community AMIs after searching for "salmon":
<img width="876" alt="Screen Shot 2021-03-25 at 3 28 53 PM" src="https://user-images.githubusercontent.com/1320475/112539296-d2628600-8d7e-11eb-99b1-f4f91b103ab8.png">

**Comment by crcox** [comment]
Ugh--I am not. It didn't occur to me why that part of the documentation should matter... but now I see I am not nearly clever enough to improvise... thanks.

**Comment by stsievert** [comment]
Thanks for the suggestion – I'll include a warning in #104.
