### ISSUE TITLE
[feature request] Validation sampling

### ISSUE THREAD

**Issue by kushinm** [stsievert/salmon#111]
Request for a mode that allows us to validate embeddings from a round of data collection by showing the exact same sets of triplets to a new set of participants to measure inter-rater reliability.

**Comment by stsievert** [comment]
When are you interested in asking these validation queries? Randomly interspersed with other questions, or separately at the very end/beginning?

**Comment by stsievert** [comment]
Apparently, the requirements are:

1. Random choice of validation sampling (intermixed with other algorithms; not at beginning/finish).
2. Query ordering:
    * Ask queries in the list (with a single pointer; nothing user-specific).
    * When end of list reached: shuffle list, repeat.
3. Query specification:
    * The *number* of validation queries ("the most common use case")
    * The specific queries (useful in filtering out bad actors).

That seems pretty straightforward.

**Comment by kushinm** [comment]
Can you update/point to docs for the new feature?

**Comment by stsievert** [comment]
The docs can be found in #112 (they're not merged yet). There's a usage example in [algorithms.rst][1] (which will eventually be rendered at https://docs.stsievert.com/salmon/algorithms.html), and the API docs are at

[1]:https://github.com/stsievert/salmon/blob/3e861af75068620fe844bae446d9439ae95749cf/docs/source/algorithms.rst

https://github.com/stsievert/salmon/blob/3e861af75068620fe844bae446d9439ae95749cf/salmon/triplets/samplers/_validation.py#L12-L29
