### ISSUE TITLE
/reset and docker-compose build doesn't reset user and password

### ISSUE THREAD

**Issue by crcox** [stsievert/salmon#115]
I pulled Salmon from GitHub and ran `docker-compose build && docker-compose up` to successfully get things running on my local machine. I input a username and password, and successfully started an experiment. I am iterating with setting up and tearing down experiments experimenting with CSS parameters, image sizes, etc. 

I've noticed that I am not being asked to reset my username and password after a `/reset?force=1`. That's fine.

However, I just did `/reset?force=1` followed by `docker-compose stop && docker-compose build && docker-compose up` and the username and password are still remembered from the last time.

This, of course, would not be a problem if I was on EC2 and terminated the instance completely and launched a new AMI. But, for people not working in the EC2 virtual server setting, is there be a way to completely reset to a new install?

If there is not, should there be?

**Comment by stsievert** [comment]
Hm... good question. I see two choices:

1. Add documentation saying "the username/password can not be changed and will be static on this machine."
2. Reset the username/password in /reset.

Given that the username/password is written to a file and only one user is allowed, I prefer option (1). The username/password is written to a file, so I should detail how to recover that file with the SSH key file (which should be at `/home/ubuntu/salmon/creds.json`).

**Comment by stsievert** [comment]
Reopening because file renaming is really easy (which is implemented in #125, which significantly improves resetting).
