### ISSUE TITLE
Fails to run local installation

### ISSUE THREAD

**Issue by jorgedch** [stsievert/salmon#135]
### Functionality
https://github.com/openjournals/joss-reviews/issues/4517

- [ ] **Installation:**

1. Fails to run local installation command `docker-compose build` on Mac OS 12.4:

```
#0 110.6   Attempting uninstall: pyyaml
#0 110.6     Found existing installation: PyYAML 5.1.2
#0 110.6 Pip subprocess error:
#0 110.6 ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
#0 110.6
#0 110.6
#0 110.6 failed
#0 110.6
#0 110.6 CondaEnvException: Pip failed
#0 110.6
------
failed to solve: executor failed running [/bin/sh -c conda env update -n base --file /salmon/salmon.yml --prune]: exit code: 1
```

**Comment by stsievert** [comment]
Hm... I can't reproduce.

<details>
<summary>Reproduction process</summary>

The command `conda env create -f salmon.yml` completed successfully for me with `conda 4.10.3`, the version [specified in the Dockerfile][1].

Building the container also worked for me (with Docker Desktop on macOS 10.14). I ran these commands:

``` shell
git clone https://github.com/stsievert/salmon.git
cd salmon
docker-compose build
docker-compose up -d --remove-orphans
```

[1]:https://github.com/stsievert/salmon/blob/534ee6b6eb29cb81805a39a814ef55465198fca5/Dockerfile#L1

</details>

I've deployed a fix in ced3cce in #139 (which is also the latest release). Do you want to try that commit and see if it works?

**Comment by stsievert** [comment]
Perhaps a better question... why are you trying to build the Docker containers locally? Email me at joss@stsievert.com with the email address you'd like me to use with Amazon AWS; with that, I can enable running through the install process at https://docs.stsievert.com/salmon/installation.html#experimentalist.

**Comment by jorgedch** [comment]
Yes, I run the commands that you mention (so it is already the latest release), but it was getting stuck in the `docker-compose build` step:

```
git clone https://github.com/stsievert/salmon.git
cd salmon
docker-compose build
```

I've been running this process as it is included in the [installation](https://docs.stsievert.com/salmon/installation.html#local-machine) docs, but you are right, this step is indicated as relevant for developers and not for experimentalists. That being said, after pulling your latest changes in the `review-comments` branch (https://github.com/stsievert/salmon/pull/139) it installs and runs correctly, so from all sides we can close this issue :)
